spring.application.name=spring-ai-test

# NVIDIA Build (OpenAI-compatible API)
spring.ai.openai.api-key=${NVIDIA_API_KEY}
spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1
spring.ai.openai.chat.model=meta/llama-3.1-70b-instruct




spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.database=postgresql
spring.jpa.show-sql=true

spring.datasource.url= jdbc:postgresql://localhost:5432/ai_accountant
spring.datasource.username=postgres
spring.datasource.password=12345


telegram.bot.token=${TELEGRAM_BOT_TOKEN}